server {
    listen 80;
    server_name amx-frontend;

    root /usr/share/nginx/html;

    # Manage Angular route redirections
    location / {
        try_files $uri $uri/ /index.html =404;
    }

    location /assets/ {
    }
}
