name: Ensure branch strategy

on:
  pull_request:
    branches:
      - 'main'

jobs:

  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: ▶ Check branches
        if: github.base_ref == 'main' && github.head_ref != 'release'
        run: |
          echo "Only the 'release' branch can be merged into 'main' from a pull request"
          exit 1