name: Test pull request code

on:
  pull_request:
    branches:
      - 'release'
      - 'main'

jobs:

  test:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: ▶ Create environment file
        run: |
          echo "PG_HOST=postgres" >> .env
          echo "PG_PORT=5432" >> .env
          echo "PG_DB=amusix" >> .env
          echo "PG_USER=root" >> .env
          echo "PG_PASSWORD=root" >> .env
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> .env
          echo "YOUTUBE_API_APP_NAME=${{ secrets.YOUTUBE_API_APP_NAME }}" >> .env
      - name: ▶ Run dockerized database
        run: docker run --name postgres -e POSTGRES_USER=root -e POSTGRES_PASSWORD=root -p "5432:5432" -d postgres:18-alpine
      - name: ▶ Create Docker network
        run: |
          docker network create amusix-network
          docker network connect amusix-network postgres
      - name: ▶ Run dockerized application
        run: docker compose up -d --build
      - name: ▶ Run backend tests
        uses: cypress-io/github-action@v7
        with:
          working-directory: tests/
          wait-on: http://localhost:2026/api/
          spec: cypress/e2e/backend/**/*
          config: baseUrl=http://localhost:2026/api
          browser: edge